// <auto-generated />
using System;
using System.Collections.Generic;
using ExchangeRateProvider.Infrastructure.Sql.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExchangeRateProvider.Infrastructure.Sql.Migrations.ExchangeRateProvider
{
    [DbContext(typeof(ExchangeRateProviderDbContext))]
    [Migration("20251015145254_Add_RatingMethod_To_Market_And_TraidingPair")]
    partial class Add_RatingMethod_To_Market_And_TraidingPair
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExchangeRateProvider.Domain.Consumers.Entities.Consumer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apikey")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("UpdatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WhiteListIps")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifierUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Consumer", "dbo");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Consumers.Entities.ConsumerMarket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ConsumerId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int");

                    b.Property<int>("MarketId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty<Dictionary<string, object>>("SpreadOptions", "ExchangeRateProvider.Domain.Consumers.Entities.ConsumerMarket.SpreadOptions#SpreadOptions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal?>("LowerLimitPercentage")
                                .HasColumnType("decimal(18, 2)")
                                .HasColumnName("LowerLimitPercentage");

                            b1.Property<bool>("SpreadEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(false)
                                .HasColumnName("SpreadEnabled");

                            b1.Property<decimal?>("UpperLimitPercentage")
                                .HasColumnType("decimal(18, 2)")
                                .HasColumnName("UpperLimitPercentage");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifierUserId");

                    b.HasIndex("MarketId");

                    b.ToTable("ConsumerMarket", "dbo");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Consumers.Entities.ConsumerPair", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ConsumerId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int");

                    b.Property<int>("MarketId")
                        .HasColumnType("int");

                    b.Property<int>("PairId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty<Dictionary<string, object>>("SpreadOptions", "ExchangeRateProvider.Domain.Consumers.Entities.ConsumerPair.SpreadOptions#SpreadOptions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal?>("LowerLimitPercentage")
                                .HasColumnType("decimal(18, 2)")
                                .HasColumnName("LowerLimitPercentage");

                            b1.Property<bool>("SpreadEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(false)
                                .HasColumnName("SpreadEnabled");

                            b1.Property<decimal?>("UpperLimitPercentage")
                                .HasColumnType("decimal(18, 2)")
                                .HasColumnName("UpperLimitPercentage");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifierUserId");

                    b.HasIndex("MarketId");

                    b.HasIndex("PairId");

                    b.ToTable("ConsumerPair", "dbo");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Consumers.Entities.ConsumerProvider", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ConsumerId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifierUserId");

                    b.HasIndex("ProviderId");

                    b.ToTable("ConsumerProvider", "dbo");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Currencies.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<int?>("DecimalPrecision")
                        .HasColumnType("int");

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<string>("Symbol")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset?>("UpdatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifierUserId");

                    b.ToTable("Currency", "dbo");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.ExchangeRateProviders.Entities.CurrencyExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Buy")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("BuyRateChange")
                        .HasColumnType("int");

                    b.Property<long>("ConsumerId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("MarketTradingPairId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("OriginalRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Sell")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SellRateChange")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId", "MarketTradingPairId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ConsumerId", "MarketTradingPairId"), false);

                    b.ToTable("CurrencyExchangeRate", "dbo");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.ExchangeRateProviders.Entities.ExchangeRateProviderApiAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Credentials")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ProtocolType")
                        .HasColumnType("int");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifierUserId");

                    b.HasIndex("ProviderId");

                    b.ToTable("ExchangeRateProviderApiAccount", "dbo");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.ExchangeRateProviders.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset?>("UpdatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifierUserId");

                    b.ToTable("ExchangeRateProviders", "dbo");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.ExchangeRateProviders.Entities.ProviderBusinessLogic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifierUserId");

                    b.HasIndex("ProviderId");

                    b.ToTable("ProviderBusinessLogic", "dbo");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Markets.Entities.Market", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseCurrencyId")
                        .HasColumnType("int");

                    b.Property<byte>("CalculationTerm")
                        .HasColumnType("tinyint");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<byte>("RatingMethod")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset?>("UpdatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty<Dictionary<string, object>>("SpreadOptions", "ExchangeRateProvider.Domain.Markets.Entities.Market.SpreadOptions#SpreadOptions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal?>("LowerLimitPercentage")
                                .HasColumnType("decimal(18, 2)")
                                .HasColumnName("LowerLimitPercentage");

                            b1.Property<bool>("SpreadEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(false)
                                .HasColumnName("SpreadEnabled");

                            b1.Property<decimal?>("UpperLimitPercentage")
                                .HasColumnType("decimal(18, 2)")
                                .HasColumnName("UpperLimitPercentage");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrencyId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("LastModifierUserId");

                    b.ToTable("Market", "dbo");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Markets.Entities.MarketCurrency", b =>
                {
                    b.Property<int>("MarketId")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.HasKey("MarketId", "CurrencyId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("MarketCurrencies", "dbo");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Markets.Entities.MarketProvider", b =>
                {
                    b.Property<int>("MarketId")
                        .HasColumnType("int");

                    b.Property<int>("ExchangeRateProviderId")
                        .HasColumnType("int");

                    b.HasKey("MarketId", "ExchangeRateProviderId");

                    b.HasIndex("ExchangeRateProviderId");

                    b.ToTable("MarketProviders", "dbo");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Markets.Entities.MarketTradingPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int");

                    b.Property<int>("MarketId")
                        .HasColumnType("int");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<byte>("RatingMethod")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset?>("UpdatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty<Dictionary<string, object>>("SpreadOptions", "ExchangeRateProvider.Domain.Markets.Entities.MarketTradingPair.SpreadOptions#SpreadOptions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal?>("LowerLimitPercentage")
                                .HasColumnType("decimal(18, 2)")
                                .HasColumnName("LowerLimitPercentage");

                            b1.Property<bool>("SpreadEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(false)
                                .HasColumnName("SpreadEnabled");

                            b1.Property<decimal?>("UpperLimitPercentage")
                                .HasColumnType("decimal(18, 2)")
                                .HasColumnName("UpperLimitPercentage");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("DeleterUserId");

                    b.HasIndex("LastModifierUserId");

                    b.HasIndex("MarketId");

                    b.ToTable("MarketTradingPair", "dbo");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Markets.Entities.MarketTradingPairProvider", b =>
                {
                    b.Property<int>("MarektTradingPairId")
                        .HasColumnType("int");

                    b.Property<int>("ExchangeRateProviderId")
                        .HasColumnType("int");

                    b.HasKey("MarektTradingPairId", "ExchangeRateProviderId");

                    b.HasIndex("ExchangeRateProviderId");

                    b.ToTable("MarketTradingPairProviders", "dbo");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Settings.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Settings", "dbo");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Users.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatorAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatorIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DeleterUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("NT.IDP.BaseIdentity.Entities.BaseRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "dbo");
                });

            modelBuilder.Entity("NT.IDP.BaseIdentity.Entities.BaseRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "dbo");
                });

            modelBuilder.Entity("NT.IDP.BaseIdentity.Entities.BaseUserBlockHistory<int, ExchangeRateProvider.Domain.Users.Entities.User, int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Blocked")
                        .HasColumnType("bit");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserRefId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBlockHistories", "dbo");
                });

            modelBuilder.Entity("NT.IDP.BaseIdentity.Entities.BaseUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "dbo");
                });

            modelBuilder.Entity("NT.IDP.BaseIdentity.Entities.BaseUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "dbo");
                });

            modelBuilder.Entity("NT.IDP.BaseIdentity.Entities.BaseUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "dbo");
                });

            modelBuilder.Entity("NT.IDP.BaseIdentity.Entities.BaseUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "dbo");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Consumers.Entities.Consumer", b =>
                {
                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId");

                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifierUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Consumers.Entities.ConsumerMarket", b =>
                {
                    b.HasOne("ExchangeRateProvider.Domain.Consumers.Entities.Consumer", "Consumer")
                        .WithMany("ConsumerMarkets")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId");

                    b.HasOne("ExchangeRateProvider.Domain.Markets.Entities.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Consumer");

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifierUser");

                    b.Navigation("Market");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Consumers.Entities.ConsumerPair", b =>
                {
                    b.HasOne("ExchangeRateProvider.Domain.Consumers.Entities.Consumer", "Consumer")
                        .WithMany("ConsumerPairs")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId");

                    b.HasOne("ExchangeRateProvider.Domain.Markets.Entities.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Markets.Entities.MarketTradingPair", "MarketTradingPair")
                        .WithMany()
                        .HasForeignKey("PairId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Consumer");

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifierUser");

                    b.Navigation("Market");

                    b.Navigation("MarketTradingPair");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Consumers.Entities.ConsumerProvider", b =>
                {
                    b.HasOne("ExchangeRateProvider.Domain.Consumers.Entities.Consumer", "Consumer")
                        .WithMany("ConsumerProviders")
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId");

                    b.HasOne("ExchangeRateProvider.Domain.ExchangeRateProviders.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Consumer");

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifierUser");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Currencies.Entities.Currency", b =>
                {
                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId");

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifierUser");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.ExchangeRateProviders.Entities.ExchangeRateProviderApiAccount", b =>
                {
                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId");

                    b.HasOne("ExchangeRateProvider.Domain.ExchangeRateProviders.Entities.Provider", "ExchangeRateProvider")
                        .WithMany("ApiAccounts")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatorUser");

                    b.Navigation("ExchangeRateProvider");

                    b.Navigation("LastModifierUser");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.ExchangeRateProviders.Entities.Provider", b =>
                {
                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId");

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifierUser");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.ExchangeRateProviders.Entities.ProviderBusinessLogic", b =>
                {
                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId");

                    b.HasOne("ExchangeRateProvider.Domain.ExchangeRateProviders.Entities.Provider", "ExchangeRateProvider")
                        .WithMany("ProviderBusinessLogics")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatorUser");

                    b.Navigation("ExchangeRateProvider");

                    b.Navigation("LastModifierUser");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Markets.Entities.Market", b =>
                {
                    b.HasOne("ExchangeRateProvider.Domain.Currencies.Entities.Currency", "BaseCurrency")
                        .WithMany()
                        .HasForeignKey("BaseCurrencyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Currencies.Entities.Currency", null)
                        .WithMany("Markets")
                        .HasForeignKey("CurrencyId");

                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId");

                    b.Navigation("BaseCurrency");

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifierUser");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Markets.Entities.MarketCurrency", b =>
                {
                    b.HasOne("ExchangeRateProvider.Domain.Currencies.Entities.Currency", "Currency")
                        .WithMany("MarketCurrencies")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Markets.Entities.Market", "Market")
                        .WithMany("MarketCurrencies")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Market");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Markets.Entities.MarketProvider", b =>
                {
                    b.HasOne("ExchangeRateProvider.Domain.ExchangeRateProviders.Entities.Provider", "ExchangeRateProvider")
                        .WithMany("MarketExchangeRateProviders")
                        .HasForeignKey("ExchangeRateProviderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Markets.Entities.Market", "Market")
                        .WithMany("MarketExchangeRateProviders")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ExchangeRateProvider");

                    b.Navigation("Market");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Markets.Entities.MarketTradingPair", b =>
                {
                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Currencies.Entities.Currency", "Currency")
                        .WithMany("MarketTradingPairs")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "DeleterUser")
                        .WithMany()
                        .HasForeignKey("DeleterUserId");

                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId");

                    b.HasOne("ExchangeRateProvider.Domain.Markets.Entities.Market", "Market")
                        .WithMany("TradingPairs")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatorUser");

                    b.Navigation("Currency");

                    b.Navigation("DeleterUser");

                    b.Navigation("LastModifierUser");

                    b.Navigation("Market");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Markets.Entities.MarketTradingPairProvider", b =>
                {
                    b.HasOne("ExchangeRateProvider.Domain.ExchangeRateProviders.Entities.Provider", "ExchangeRateProvider")
                        .WithMany("MarketTradingPairProviders")
                        .HasForeignKey("ExchangeRateProviderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Markets.Entities.MarketTradingPair", "MarketTradingPair")
                        .WithMany("MarketTradingPairProviders")
                        .HasForeignKey("MarektTradingPairId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ExchangeRateProvider");

                    b.Navigation("MarketTradingPair");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Settings.Entities.Setting", b =>
                {
                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NT.IDP.BaseIdentity.Entities.BaseRoleClaim<int>", b =>
                {
                    b.HasOne("NT.IDP.BaseIdentity.Entities.BaseRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NT.IDP.BaseIdentity.Entities.BaseUserBlockHistory<int, ExchangeRateProvider.Domain.Users.Entities.User, int>", b =>
                {
                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("CreatorUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NT.IDP.BaseIdentity.Entities.BaseUserClaim<int>", b =>
                {
                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NT.IDP.BaseIdentity.Entities.BaseUserLogin<int>", b =>
                {
                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NT.IDP.BaseIdentity.Entities.BaseUserRole<int>", b =>
                {
                    b.HasOne("NT.IDP.BaseIdentity.Entities.BaseRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NT.IDP.BaseIdentity.Entities.BaseUserToken<int>", b =>
                {
                    b.HasOne("ExchangeRateProvider.Domain.Users.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Consumers.Entities.Consumer", b =>
                {
                    b.Navigation("ConsumerMarkets");

                    b.Navigation("ConsumerPairs");

                    b.Navigation("ConsumerProviders");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Currencies.Entities.Currency", b =>
                {
                    b.Navigation("MarketCurrencies");

                    b.Navigation("MarketTradingPairs");

                    b.Navigation("Markets");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.ExchangeRateProviders.Entities.Provider", b =>
                {
                    b.Navigation("ApiAccounts");

                    b.Navigation("MarketExchangeRateProviders");

                    b.Navigation("MarketTradingPairProviders");

                    b.Navigation("ProviderBusinessLogics");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Markets.Entities.Market", b =>
                {
                    b.Navigation("MarketCurrencies");

                    b.Navigation("MarketExchangeRateProviders");

                    b.Navigation("TradingPairs");
                });

            modelBuilder.Entity("ExchangeRateProvider.Domain.Markets.Entities.MarketTradingPair", b =>
                {
                    b.Navigation("MarketTradingPairProviders");
                });
#pragma warning restore 612, 618
        }
    }
}
